#!/bin/bash -x
#SBATCH --job-name=md
#SBATCH --output=md.out
#SBATCH --err=md.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=40
#SBATCH --partition=dev_single
#SBATCH --time=00:30:00
#SBATCH --mem=6gb
#SBATCH --export=ALL

module load compiler/gnu/10.2
module load mpi/openmpi/4.1

echo "Running on ${SLURM_JOB_NUM_NODES} nodes with ${SLURM_JOB_CPUS_PER_NODE} cores each."
echo "Each node has ${SLURM_MEM_PER_NODE} of memory allocated to this job."
time mpirun ./09